NCAR/WrfHydroForcing

- .idea/NWM_v21.iml
- .idea/misc.xml
- core/dateMod.py
- core/downscaleMod.py
- core/forcingInputMod.py
- core/forecastMod.py
- core/geoMod.py
- core/ioMod.py
Various bug fixes and making sure FE can be properly restarted after failure.
> Friday May 24th Merge. 

- Template/template_forcing_engine.config
- core/biasCorrectMod.py
- core/configMod.py
- core/dateMod.py
- core/downscaleMod.py
- core/ioMod.py
- core/regridMod.py
- core/timeInterpMod.py
- genForcing.py
Testing CFSv2 NLDAS bias correction for long-range configuration.
> 5/29/2019 Merge

- Util/get_ARW_Hawaii.py
- Util/get_ARW_Puerto_Rico.py
- Util/get_CFSv2.py
- Util/get_conus_HRRR.py
- Util/get_conus_MRMS_GC.py
- Util/get_conus_MRMS_RQI.py
- Util/get_conus_MRMS_Radar.py
- Util/get_conus_RAP.py
- Util/get_prod_GFS.py
- Util/get_prod_NAM_Nest_Alaska.py
- Util/get_prod_NAM_Nest_Hawaii.py
- Util/get_prod_NAM_Nest_PuertoRico.py
- core/biasCorrectMod.py
- core/dateMod.py
Fixes for incoming SW bias correction, adding fetch utilities for NOMADS. Misc fixes, testing.....
> June 19th Merge

- Util/blend_mpe_extAnA.py
- Util/get_ARW_Hawaii.py
- Util/get_ARW_Puerto_Rico.py
- Util/get_CFSv2.py
- Util/get_conus_HRRR.py
- Util/get_conus_RAP.py
- Util/get_prod_GFS.py
- Util/get_prod_NAM_Nest_Hawaii.py
- Util/get_prod_NAM_Nest_PuertoRico.py
Updated fetch programs to run on Cheyenne. Also added a utility program that will be used in extended AnA ops workflow to blend in MPE into LDASIN.
> Merge 6/21/19

- core/errMod.py
- core/forecastMod.py
- core/ioMod.py
Two checks being put in here:
1.) Check after regridding for reasonable physical values. 
2.) A final check on the output grid to ensure NO NDV values exist.
> Adding value checks

- core/configMod.py
- core/downscaleMod.py
- core/errMod.py
- core/forcingInputMod.py
- core/forecastMod.py
- core/geoMod.py
- core/ioMod.py
- core/layeringMod.py
- core/parallelMod.py
- core/regridMod.py
Here are my initial changes. The code for direct grib reads is present but not active yet.
> Inital changes in optimizing forcing engine.

- core/configMod.py
- core/downscaleMod.py
- core/errMod.py
- core/forcingInputMod.py
- core/forecastMod.py
- core/geoMod.py
- core/ioMod.py
- core/layeringMod.py
- core/parallelMod.py
- core/regridMod.py
Reverts NCAR/WrfHydroForcing#21. Need to re-apply this commit after some refactoring commits.
> Revert "Inital changes in optimizing forcing engine."

- core/forcingInputMod.py
- core/geoMod.py
- core/parallel.py
- Updated scaterv logic to not use cache. 
- Updated scatter_array to be wrapper around different scatter implementations.
> Add back old scatter_array routine with option to use new

- core/parallel.py
Use the previous version of `scatter_array`
> Use old `scatter_array` function

- core/regrid.py
Additional fix to parameter orders, this time in supplemental precip weight calculation.
> Additional parameter-order fix

- Template/template_forcing_engine.config
- core/bias_correction.py
- core/config.py
- core/downscale.py
- core/err_handler.py
- core/geoMod.py
- core/ioMod.py
- core/parallel.py
- core/regrid.py
- core/time_handling.py
Added additional bias-correction routines developed at NCAR for HRRR and GFS in AnA, Short-Range, and Medium-Range configurations.
> Bias Correction Updates for GFS and HRRR

- Template/template_forcing_engine.config
- core/bias_correction.py
- core/config.py
- core/forecastMod.py
- core/ioMod.py
- core/regrid.py
- core/suppPrecipMod.py
- core/time_handling.py
- genForcing.py
This code adds the remaining Bias Correction routines as well as correcting issues in the AnA support (lookback, labelling, forecast->analysis time shifting)
> Updates for Bias Correction and AnA Support

- core/config.py
- core/forecastMod.py
- core/time_handling.py
* keep cycles together; don't use hours from multiple cycles even if newer
* don't use forecast hours f00-f03 due to spin-up issues
> Implement changes for NAM AnA cycling

- Template/template_forcing_engine.config
- core/config.py
- core/ioMod.py
- core/regrid.py
- core/suppPrecipMod.py
- core/time_handling.py
Code to support the new Pass1/Pass2 multisensor MRMS v12 updaates.
> MRMS updates

- core/forcingInputMod.py
- core/time_handling.py
Add basic support for NLDAS2 ingest. Tested with netCDF; _should_ work with GRIB2. There's no current way to directly read the GRIB1 data, though.
> Add support for NLDAS2

- core/bias_correction.py
Update to bias_correction.py to add Joe Grim's bias correction equations
> Update bias_correction.py with new HRRR bias correction equations

- core/bias_correction.py
Change `bias_corr`  to `wspd_bias_corr`
> Fix typo in HRRR wspd bias correction

- Template/template_forcing_engine.config
- core/config.py
- core/err_handler.py
- core/forecastMod.py
- core/ioMod.py
- core/layeringMod.py
- core/parallel.py
- core/regrid.py
- core/suppPrecipMod.py
- core/time_handling.py
Add the ability to read in MRMS SBCv2 Liquid Water Fraction data and layer it in to the WRF-Hydro forcing files.
> Add Liquid Water Fraction processing capability

- core/config.py
- core/regrid.py
- core/suppPrecipMod.py
- core/time_handling.py
Add support for time-limited NBM Supplemental Precipitation input for the NWM Alaska Short-Range configuration.
> NWM Alaska Short-Range support

- core/time_handling.py
Integrate Cham's updates for WCOSS2. Note: this may require some rearrangement of test data on Cheyenne.
> Update time_handling.py for WCOSS2 support

- core/time_handling.py
Additional fixes for NBM precip support in Alaska short-range configuration
> AK Short-Range NBM support

- core/config.py
- core/forcingInputMod.py
- core/regrid.py
- core/suppPrecipMod.py
- core/time_handling.py
Allow NBM to be used for primary meteorological forcing instead of only as supplemental precipitation
> Support NBM as primary forcing input

- Template/template_forcing_engine.config
- core/config.py
- core/downscale.py
- core/err_handler.py
- core/forcingInputMod.py
- core/forecastMod.py
- core/ioMod.py
- core/parallel.py
- core/regrid.py
- core/time_handling.py
* support National Digital Forecast Database (in WCOSS format)
* fix broken support for nearest-neighbor interpolation in ESMF
* various small changes to logging messages
> Support NDFD as input forcing

- core/config.py
- core/downscale.py
- core/regrid.py
Compute a dynamic lapse rate from RAL temperature and geopotential height from surface to hybrid level 12. Use this lapse rate in HRRR as well.
> Add RAP-based dynamic lapse rate

- Config/WCOSS/v3.0/template_forcing_engine_2min.config
- Config/WCOSS/v3.0/template_forcing_engine_Alaska_Analysis.config
- Config/WCOSS/v3.0/template_forcing_engine_Analysis.config
- Config/WCOSS/v3.0/template_forcing_engine_GFS_13KM.config
- Config/WCOSS/v3.0/template_forcing_engine_HRRR15min.config
- Config/WCOSS/v3.0/template_forcing_engine_Hawaii_Analysis.config
- Config/WCOSS/v3.0/template_forcing_engine_Hawaii_Short.config
- Config/WCOSS/v3.0/template_forcing_engine_Long.config
- Config/WCOSS/v3.0/template_forcing_engine_Medium.config
- Config/WCOSS/v3.0/template_forcing_engine_Medium_Blend.config
- Config/WCOSS/v3.0/template_forcing_engine_PuertoRico_Analysis.config
- Config/WCOSS/v3.0/template_forcing_engine_PuertoRico_Short.config
- Config/WCOSS/v3.0/template_forcing_engine_Short.config
- core/config.py
- core/downscale.py
- core/forcingInputMod.py
- core/forecastMod.py
- core/ioMod.py
- core/parallel.py
- core/regrid.py
- core/suppPrecipMod.py
- core/time_handling.py
Adding code changes and configs related to extension of GFS, Short Range, HRRR15 min, MRMS 2min NWMV3.0 tasks.
> NWMV3.0 work added with previous commit history

- Config/WCOSS/v3.0/template_forcing_engine_Alaska_Analysis.config
- Config/WCOSS/v3.0/template_forcing_engine_Analysis.config
- Config/WCOSS/v3.0/template_forcing_engine_Hawaii_Analysis.config
- Config/WCOSS/v3.0/template_forcing_engine_Hawaii_Short.config
- Config/WCOSS/v3.0/template_forcing_engine_Long.config
- Config/WCOSS/v3.0/template_forcing_engine_Medium.config
- Config/WCOSS/v3.0/template_forcing_engine_Medium_Blend.config
- Config/WCOSS/v3.0/template_forcing_engine_PuertoRico_Analysis.config
- Config/WCOSS/v3.0/template_forcing_engine_PuertoRico_Short.config
- Config/WCOSS/v3.1/template_forcing_engine_2min.config
- Config/WCOSS/v3.1/template_forcing_engine_Alaska_Analysis.config
- Config/WCOSS/v3.1/template_forcing_engine_Alaska_ExtAnalysis.config
- Config/WCOSS/v3.1/template_forcing_engine_Alaska_Medium.config
- Config/WCOSS/v3.1/template_forcing_engine_Alaska_Medium_Blend.config
- Config/WCOSS/v3.1/template_forcing_engine_Alaska_Short.config
- Config/WCOSS/v3.1/template_forcing_engine_Analysis.config
- Config/WCOSS/v3.1/template_forcing_engine_GFS_13KM.config
- Config/WCOSS/v3.1/template_forcing_engine_HRRR15min.config
- Config/WCOSS/v3.1/template_forcing_engine_Hawaii_Analysis.config
- Config/WCOSS/v3.1/template_forcing_engine_Hawaii_Short.config
- Config/WCOSS/v3.1/template_forcing_engine_Long.config
- Config/WCOSS/v3.1/template_forcing_engine_Medium.config
- Config/WCOSS/v3.1/template_forcing_engine_Medium_Blend.config
- Config/WCOSS/v3.1/template_forcing_engine_PuertoRico_Analysis.config
- Config/WCOSS/v3.1/template_forcing_engine_PuertoRico_Short.config
- Config/WCOSS/v3.1/template_forcing_engine_Short.config
- core/ioMod.py
- core/regrid.py
Add NBM logging per email request
Split out v3.0 and v3.1 template directories
Update SR/MR output lengths
> V3.1 updates

- Config/WCOSS/v3.1/template_forcing_engine_PuertoRico_Short.config
- core/config.py
- core/suppPrecipMod.py
- core/time_handling.py
For 00z and 12z PR cycles, shift back 6 hours to 18z and 06z WRF-ARW Hires runs.
Support .pr. CORE NBM input
> Support off-cycle WRF-ARW and NBM for PR

- Config/WCOSS/v3.0/template_forcing_engine_Alaska_Medium_Blend.config
- Config/WCOSS/v3.1/template_forcing_engine_Medium_GFS-Blend.config
- core/time_handling.py
* Shift RAP only when needed
* Limit Blend inputs and only log error if files are missing that were otherwise expected
> Various last-minute fixes to v3.1 ops

- core/time_handling.py
Don't shift RAP cycle for AnA within time_handling (it's dealt with in genForcing)
> Fix incorrect RAP cycle

- core/time_handling.py
Remove 3-hour lookback for every-6-hour RAP cycles
> Roll back RAP cycle shifting

- core/regrid.py
Use NaN when masking missing liquid fraction to prevent interpolation errors
> Use NaN-based masking for liquid fraction
