- core/dateMod.py
- core/forcingInputMod.py
- core/regridMod.py
- core/timeInterpMod.py
Put in logic to handle the asinine way GFS places their precipitation rates into the operational sfc flux GRIB2 files. Logic will use previous avg window to calculate an instantaneous precipitation rate. These are then regridded and interpolated for processing.
> GFS Precip Rate Differencing

- core/forcingInputMod.py
- core/forecastMod.py
- core/ioMod.py
- core/regrid.py
- core/suppPrecipMod.py
Instead of creating a new temporary NetCDF file for each GRIB input field, convert them all in one call to `wgrib2` and then leave the resulting netCDF file open while looping over all the input fields. This change has been added to all the CONUS-level regridders (HRRR, RAP, CFSv2, and GFS). This results in an approximately 30% speed-up vs. the previous method.
> GRIB-to-netCDF optimization

- core/parallel.py
- core/regrid.py
- core/time_handling.py
Some calls to check_regrid_status() had the wrong parameter order. This PR should make them all consistent.
Also, this removes an unnecessary / incorrect "+1" when calculating `nFcsts`
> Correct parameter order in check_regrid_status() calls

- core/regrid.py
Parameter order changed for calculate_weights and the call was inconsistently updated. This PR fixes that. Ideally, we should use type-checking for these calls.
> Correct inconsistency in calculate_weights() parameter order

- core/regrid.py
When GFS goes from 1-hourly to 3-hourly forecasts, reuse the previously converted netCDF version instead of reconverting.
> Reuse 3hr GFS files

- core/bias_correction.py
Fix issue with missing `MM` variable in HRRR ncar_wspd_bias_correct function
> Add missing MM (month) to ncar_wspd_bias_correct()

- core/bias_correction.py
When applying HRRR bias corrections in AnA mode, the wrong hour is used in parameter calculation. This PR fixes that by subtracting one hour from the original value in AnA mode.
> Adjust AnA bias correction hour to compensate for forecast shift

- core/ioMod.py
When generating AnA output, use the `model_initialization_time` (final hour) instead of the model analysis hour for the `model_output_valid_time` global attribute.
> Update AnA valid time to initalization time

- core/config.py
- core/regrid.py
- core/suppPrecipMod.py
This update adds the ability to supply independent RQIMethod parameters for each supplied Supplemental Precipitation forcing used. The initial use-case for this is to allow Radar-Only MRMS to be used (with RQI filtering) when MRMS Pass1/Pass2 data are not available. Supplying a single RQIMethod would cause the MRMS Pass1/2 data to be filtered, which it should not be.
> Allow RQIMethod to be applied per-input in Supplemental Precipitation

- core/time_handling.py
When the RAP `bgrb` file is missing, a matching `pgrb` file is searched for. The code that handles this incorrectly runs only on MPI rank 0, leading to a mis-synchronization and hang in subsequent MPI code. This PR fixes that by moving the rank == 0 check to only apply the output messaging.
> Fix RAP bgrb/pgrb fallback to run on all MPI ranks

- core/regrid.py
- core/suppPrecipMod.py
This fixes two issues:
- Code that tests for rqiMethod or rqiThreshold fail for suppPrecip that doesn't use RQI (like MRMS), because no default value was specified 
- MRMS regrid() was not testing for rqiMethod > 0 and comparing against rqiThreshold anyway (This really should be removed but I'm leaving it for now in case it's ever used in the future)
> Set RqiMethod=0 by default

- core/bias_correction.py
Warnings occurred during HRRR shortwave radiation bias correction where values passed to arccos could be very slightly greater than 1.0. This change bounds the result of the upstream calcuation to [-1,1] to eliminate the warning.
> Bound arccos argument in ncar_sw_hrrr_bias_correct to [-1,1]

- core/ioMod.py
The `model_initialization_time` should always be the first hour of the simulation time, with no special handling of the AnA lookback case.
> Use consistent model init time with AnA / Fcst

- core/ioMod.py
Cycle time for AnA is the same as the first file (as opposed to f000/t001 in forecasts), so the `model_initialization_time` needs to be set back one hour for AnA.
> Correct AnA model_initialization_time off an hour

- Template/template_forcing_engine.config
- core/config.py
- core/ioMod.py
Add an option to the config file to enable/disable LQFRAC output. Output will be disabled by default.
> Add config option to enable LQFRAC output

- core/ioMod.py
Copy (most of*) the spatial metadata into the globals of the output forcings. 
*don't copy the GIS PreProcessor-specific stuff
> Add spatial metadata globals to output files

- core/ioMod.py
Change the `model_total_valid_times` from a 64-bit float to a 32-bit integer, for consistency with other NWM output files.
> Change `model_total_valid_times` attrib to int32

- core/config.py
- core/forecastMod.py
- core/ioMod.py
* Change globalNdv / netCDF missing_value from -9999 to -999999, to avoid scaled winds getting marked as invalid
* Add `version` to ignored global metadata attributes to avoid confusion, since the FE already adds a similar attribute
> Update missing value and and ignore global metadata

- core/bias_correction.py
The _FillValue in the NLDAS params needs to be explicity changed to the globalNdv value so the masked areas can be reconstructed on the other side of an MPI broadcast
> Don't mask NLDAS params when reading netCDF var

- core/downscale.py
- core/geoMod.py
- core/regrid.py
- genForcing.py
* It was found on WCOSS2 that netCDF4 needed to be loaded _before_ ESMF. This reorders those imports where appropriate.
* Newer ESMF versions are now imported as `esmpy`, so code was added to support both old and new names
> Reorder import statements, support newer esmpy vesions

- core/downscale.py
- core/regrid.py
* use NaN masking for GFS CPOFP when regridding LQFRAC
* initialize Mountain Mapper grid to existing `RAINRATE` grid so unmodified values pass through instead of being replaced with -9999
> GFS updates

- core/downscale.py
The Mountain Mapper downscaling routine was dividing rain rate by 3600, which was an error since it was already a rate and not an accumulation as assumed.
> Remove extra precip rate conversion from Mountain Mapper
